# Generated by Django 5.0.4 on 2024-09-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
