# Generated by Django 5.0.4 on 2024-04-24 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
