# Generated by Django 5.0.4 on 2024-04-14 02:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
