# Generated by Django 5.0.4 on 2024-09-26 07:47

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_receipt_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCardTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=255)),
                ('number_plate', models.CharField(max_length=50)),
                ('image_mrc_m1', cloudinary.models.CloudinaryField(max_length=255, null=True)),
                ('image_mrc_m2', cloudinary.models.CloudinaryField(max_length=255, null=True)),
                ('image_idcard_m1', cloudinary.models.CloudinaryField(max_length=255, null=True)),
                ('image_idcard_m2', cloudinary.models.CloudinaryField(max_length=255, null=True)),
                ('active', models.BooleanField(default=False)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.flat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
