# Generated by Django 5.0.4 on 2024-05-16 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_remove_complaint_tag_complaint_complaint_tag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='tag',
            new_name='status_tag',
        ),
    ]
