# Generated by Django 5.0.4 on 2024-04-14 03:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_alter_complaint_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecabinet',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='flat',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='ecabinet',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ecabinet',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ecabinet',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='flat',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='flat',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
