# Generated by Django 5.0.4 on 2024-10-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_alter_choice_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='due_date',
        ),
    ]
