# Generated by Django 5.0.4 on 2024-05-24 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_complainttag_statustag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='ComplaintTag',
        ),
        migrations.DeleteModel(
            name='StatusTag',
        ),
        migrations.AddField(
            model_name='tag',
            name='type_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apartments.typetag'),
        ),
    ]
