# Generated by Django 5.0.4 on 2024-05-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_typetag_delete_complainttag_delete_statustag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='type_tag',
        ),
        migrations.DeleteModel(
            name='TypeTag',
        ),
    ]
