# Generated by Django 5.0.4 on 2024-04-14 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0007_tag_comment_item_survey_receipt_complaint_tag_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcard',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.flat'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.complaint'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flat',
            name='e_cabinet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='apartments.ecabinet'),
        ),
        migrations.AlterField(
            model_name='item',
            name='e_cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.ecabinet'),
        ),
        migrations.AlterField(
            model_name='like',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.complaint'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.flat'),
        ),
    ]
