# Generated by Django 5.0.4 on 2024-06-10 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0015_remove_user_phone_number_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='ecabinet',
        ),
        migrations.AddField(
            model_name='ecabinet',
            name='phone_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='apartments.phonenumber'),
        ),
    ]
