# Generated by Django 5.0.4 on 2024-06-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0018_alter_answeruser_user_alter_question_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='order_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
