# Generated by Django 5.0.4 on 2024-06-15 13:16

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0020_paymentdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetail',
            name='receipt',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='apartments.receipt'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
