# Generated by Django 5.0.4 on 2024-06-16 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0022_remove_survey_status_surveyuserdone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='surveyuserdone',
            options={'ordering': ['-created_date']},
        ),
        migrations.RemoveField(
            model_name='survey',
            name='status',
        ),
    ]
