# Generated by Django 5.0.4 on 2024-06-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0022_remove_survey_status_surveyuserdone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='survey_done',
            field=models.ManyToManyField(related_name='survey_done', to='apartments.survey'),
        ),
    ]
