# Generated by Django 5.0.4 on 2024-06-16 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0023_alter_surveyuserdone_options_remove_survey_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='survey_user_done',
        ),
    ]
