# Generated by Django 5.0.4 on 2024-06-15 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0023_user_survey_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='survey_done',
        ),
    ]
